package basicIntro;	
					// PACKAGE IS 1st LINE IN PROGRAMME.
					// IT CONSIST OF n NO OF CLASSES WITH DIFFERENT NAME.
					// SYNTAX===> package "packageName" [1st LETTER OF PACKAGE NAME MUST BE SMALL]

public class IntroOfPackageAndClass 

					// PUBLIC ===> ACCESS MODIFIER & PREDEFINED KEYWORD.
					// class ====> IT IS ALSO PREDEFINED KEYWORD IN JAVA LIBRARY.
					// SYNTAX====> public class ClassName [1st LETTER OF EACH WORD IN NAME MUST BE CAPITAL

{					// THIS IS CLASS BODY/BLOCK

	public static void main (String[] args) 
	
						// MAIN METHOD 
	
						// PUBLIC ===> ACCESS MODIFIER & PREDEFINED KEYWORD.
						//STATIC====> // static IS PREDEFINED KEYWORD WHICH IS USED TO RUN PROGRAMME WITHOUT OBJECT.
						// VOID====> RETURN TYPE IS NULL
						// ((String[] args))====> 
						//THIS IS THE ARRAY OF STRINGS WHICH IS TO BE PROVIDED TO CONSOLE THROUGH MAIN METHOD.
						// MAIN METHOD IS ONLY USED TO NAVIGATE THE INFORMATION AS PER SEQUENCE REQUIRED BY THE USER.
						//WITHOUT MAIN METHOD ANY PROGRAMME WILL NOT AT ALL RUN IN CONSOLE.
	
	{
	
		System.out.println("THIS IS INTRODUCTION OF PACKAGE & CLASS"); //PRINT STATEMENT
													
						//SYSTEM ====> UTILITY CLASS WHICH IS PREDEFINED.
						//.OUT====> OBJECT OF UTILITY CLASS
						// PRINTLN====> METHOD WHICH IS USED TO PRINT THE INFORMATION TO CONSOLE WHICH IS WRITTEN IN METHOD SIGN.
		
		
	}
}
